---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    ssh_user: centos
    ssh_port: 22

    security_group_description: Security group for testing Molecule
    security_group_rules:
      - proto: tcp
        from_port: "{{ ssh_port }}"
        to_port: "{{ ssh_port }}"
        cidr_ip: '0.0.0.0/0'
      - proto: icmp
        from_port: 8
        to_port: -1
        cidr_ip: '0.0.0.0/0'
    security_group_rules_egress:
      - proto: -1
        from_port: 0
        to_port: 0
        cidr_ip: '0.0.0.0/0'
    keypair_path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"

  tasks:
    - name: Create security group
      amazon.aws.ec2_group:
        name: "{{ item.security_group_name }}"
        description: "{{ item.security_group_name }}"
        rules: "{{ security_group_rules }}"
        rules_egress: "{{ security_group_rules_egress }}"
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index
      register: security_group

    - name: Test for presence of local keypair
      ansible.builtin.stat:
        path: "{{ keypair_path }}"
      register: keypair_local

    - name: Delete remote keypair
      amazon.aws.ec2_key:
        name: "{{ item.keypair_name }}"
        state: absent
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index
      when: not keypair_local.stat.exists

    - name: Create keypair
      amazon.aws.ec2_key:
        name: "{{ item.keypair_name }}"
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index
      register: keypair

    - name: Persist the keypair
      ansible.builtin.copy:
        dest: "{{ keypair_path }}"
        content: "{{ keypair.results[0].key.private_key }}"
        mode: 0600
      when: keypair.results[0].msg == "key pair created"

    - name: Get the ec2 ami(s) by owner and name, if image not set
      amazon.aws.ec2_ami_facts:
        owners: "{{ item.image_owner }}"
        filters:
          name: "{{ item.image_name }}"
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index
      when: item.image is not defined
      register: ami_facts

    - name: Create molecule instance(s)
      amazon.aws.ec2:
        key_name: "{{ item.keypair_name }}"
        image: "{{ item.image }}"
        instance_type: "{{ item.instance_type }}"
        vpc_subnet_id: "{{ item.vpc_subnet_id }}"
        group: "{{ item.security_group_name }}"
        instance_tags:
          created_by: "{{ item.tag_created_by }}"
          instance: "{{ item.tag_name }}"
          Name: "{{ item.tag_name }}"
        wait: true
        assign_public_ip: true
        exact_count: 1
        count_tag:
          instance: "{{ item.name }}"
      register: server
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index
      async: 7200
      poll: 0

    - name: Wait for instance(s) creation to complete
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: ec2_jobs
      until: ec2_jobs.finished
      retries: 300
      with_items: "{{ server.results }}"

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config dict
      ansible.builtin.set_fact:
        instance_conf_dict: {
          'instance': "{{ item.instances[0].tags.instance }}",
          'address': "{{ item.instances[0].public_ip }}",
          'user': "{{ ssh_user }}",
          'port': "{{ ssh_port }}",
          'identity_file': "{{ keypair_path }}",
          'instance_ids': "{{ item.instance_ids }}",
          'group_id': "{{ security_group.results[0].group_id }}", }
      with_items: "{{ ec2_jobs.results }}"
      register: instance_config_dict
      when: server.changed | bool

    - name: Convert instance config dict to a list
      ansible.builtin.set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
      when: server.changed | bool

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | community.molecule.to_yaml }}"
        dest: "{{ molecule_instance_config }}"
        mode: 0600
      when: server.changed | bool

    - name: Wait for SSH
      wait_for:
        port: "{{ ssh_port }}"
        host: "{{ item.address }}"
        search_regex: SSH
        delay: 10
        timeout: 320
      with_items: "{{ lookup('file', molecule_instance_config) | community.molecule.from_yaml }}"

    - name: Wait for boot process to finish
      pause:
        minutes: 2
