---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ghcr.io/docker-hub-tm/ansible-test/${MOLECULE_DISTRO:-centos7}:latest
    pre_build_image: True
    command: /sbin/init
    privileged: True
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: ansible.posix.profile_tasks
  connection_options:
    linux_user: test
    linux_groups: docker
verifier:
  name: ansible
scenario:
  test_sequence:
    - syntax
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
