---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Gather facts
      ansible.builtin.setup:
      register: results
      delegate_to: localhost

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: "{{ lookup('file', molecule_instance_config) | from_yaml }}"

    - name: Set fact for Public IP
      ansible.builtin.set_fact:
        public_ip: "{{ item.address }}"
      with_items: "{{ instance_conf }}"

    - name: Check if SSH connection is possible
      ansible.builtin.command:
        cmd: "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /home/circleci/.ssh/id_rsa ansible@{{ public_ip }} whoami"
      register: ssh_results
      changed_when: false
      delegate_to: localhost

    - name: Debug var
      ansible.builtin.debug:
        var: ssh_results
    - name: Check whether Linux user is created
      ansible.builtin.shell: |
        set -o pipefail
        ls -l /home | grep {{ linux_user }}
      args:
        executable: /bin/bash
      register: user_exists
      changed_when: false

    - name: Make sure Linux user is created
      ansible.builtin.assert:
        that:
          - "'{{ linux_user }}' in user_exists.stdout"

    - name: Debug var
      ansible.builtin.debug:
        var: user_exists

    - name: Check whether Linux user belongs to 'docker' group
      ansible.builtin.shell: |
        set -o pipefail
        groups {{ linux_user }} | grep docker
      args:
        executable: /bin/bash
      register: user_groups_belongs_to
      changed_when: false

    - name: Make sure Linux user belongs to 'docker' group
      ansible.builtin.assert:
        that:
          - "'{{ linux_groups }}' in user_groups_belongs_to.stdout"

    - name: Debug var
      ansible.builtin.debug:
        var: user_groups_belongs_to

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
