---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Check whether Linux user is created
      ansible.builtin.shell: |
        set -o pipefail
        ls -l /home | grep {{ linux_user }}
      args:
        executable: /bin/bash
      register: user_exists
      changed_when: false

    - name: Make sure Linux user is created
      ansible.builtin.assert:
        that:
          - "'{{ linux_user }}' in user_exists.stdout"

    - name: Debug var
      debug:
        var: user_exists

    - name: Check whether Linux user belongs to 'docker' group
      ansible.builtin.shell: |
        set -o pipefail
        groups {{ linux_user }} | grep docker
      args:
        executable: /bin/bash
      register: user_groups_belongs_to
      changed_when: false

    - name: Make sure Linux user belongs to 'docker' group
      ansible.builtin.assert:
        that:
          - "'{{ linux_groups }}' in user_groups_belongs_to.stdout"

    - name: Debug var
      debug:
        var: user_groups_belongs_to

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
