---
- name: Create user accounts
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default(omit) }}"
  loop: '{{ users }}'

- name: Add authorized keys
  ansible.posix.authorized_key:
    user: '{{ item.name }}'
    key: '{{ item_key }}'
  loop: '{{ users }}'
  vars:
    authorized_keys: '{{ item.authorized_keys | default([]) }}'
    item_key: '{{ authorized_keys | first }}'
  when: authorized_keys | length > 0
