---
version: 2.1

executors:
  molecule:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/trailing-whitespace:latest
    resource_class: small

orbs:
  ansible-lint: orbss/ansible-lint@0.0.3
  yamllint: orbss/yamllint@0.0.4

jobs:
  ansible-lint:
    executor: ansible-lint/default
    steps:
      - checkout
      - ansible-lint/execute:
          molecule-role-test: true
  molecule:
    executor: molecule
    parameters:
      checkout-path:
        type: string
      molecule-test-image:
        type: string
      molecule-scenario-name:
        type: string
    steps:
      - checkout:
          path: << parameters.checkout-path >>
      - run:
          name: Generate Ansible variable file
          command: |
            cd << parameters.checkout-path >>
            pub_key=$(cat $HOME/.ssh/id_rsa.pub)
            working_dir=$(pwd)
            sed -i "s/id_rsa.pub/${pub_key}/" "${working_dir}/molecule/variable_template.yml"
            mv "${working_dir}/molecule/variable_template.yml" "${working_dir}/defaults/main.yml"
      - run:
          name: Install requirements
          command: |
            cd << parameters.checkout-path >>
            pip3 install --user -r molecule/requirements.txt
      - run:
          name: Show Ansible version
          command: |
            export PATH="$PATH:$HOME/.local/bin/"
            ansible --version \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
      - run:
          name: Show Molecule version
          command: |
            export PATH="$PATH:$HOME/.local/bin/"
            molecule --version
      - run:
          name: Test with Molecule
          command: |
            export PATH="$PATH:$HOME/.local/bin/"
            cd << parameters.checkout-path >>
            molecule test --scenario-name << parameters.molecule-scenario-name >>
          environment:
            ANSIBLE_FORCE_COLOR: '1'
            ANSIBLE_COLLECTIONS_PATH: "/home/circleci/.local/lib/python3.9/site-packages/ansible/collections"
            MOLECULE_IMAGE: "<< parameters.molecule-test-image >>"
            PY_COLORS: '1'
            TZ: 'Asia/Tokyo'
      - run:
          name: SSH test
          command: |
            ssh -oStrictHostKeyChecking=no ansible@localhost -p 2222 "whoami; cat /etc/redhat-release"
            ssh -oStrictHostKeyChecking=no root@localhost -p 2222 "whoami; cat /etc/redhat-release"
  trailing-whitespace:
    executor: trailing-whitespace
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace
  yamllint:
    executor: yamllint/default
    steps:
      - checkout
      - yamllint/execute

workflows:
  version: 2.1
  build:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - ansible-lint:
          requires:
            - yamllint
      - molecule:
          matrix:
            parameters:
              checkout-path:
                - 'user'
              molecule-test-image:
                - 'ghcr.io/docker-images-mamono210/ansible-test/centos-stream8-ssh:latest'
                - 'ghcr.io/docker-images-mamono210/ansible-test/centos-stream9-ssh:latest'
                - 'ghcr.io/docker-images-mamono210/ansible-test/centos7-ssh:latest'
              molecule-scenario-name:
                - 'default'
                - 'group_test'
          requires:
            - ansible-lint
