---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE}
    command: /sbin/init
    privileged: true
    exposed_ports:
      - 2222/tcp
    published_ports:
      - 0.0.0.0:2222:22/tcp
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  connection_options:
    linux_user: test
verifier:
  name: ansible
scenario:
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - verify
