---
roles:
  - name: mamono210.molecule_ec2_driver
    src: https://github.com/ansible-roles-mamono210/molecule_ec2_driver.git
  - name: mamono210.docker
    src: https://github.com/ansible-roles-mamono210/docker.git
