---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Check whether Linux user is created
      ansible.builtin.shell: "ls -l /home | grep {{ linux_user }}"
      register: USER_EXISTS
      changed_when: false

    - name: Make sure Linux user is created
      ansible.builtin.assert:
        that:
          - "'{{ linux_user }}' in USER_EXISTS.stdout"

    - name: Debug var
      debug:
        var: USER_EXISTS

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: OS_VERSION
