---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Check whether Linux user is created
      ansible.builtin.shell: |
        set -o pipefail
        ls -l /home | grep {{ linux_user }}
      args:
        executable: /bin/bash
      register: user_exists
      changed_when: false

    - name: Make sure Linux user is created
      ansible.builtin.assert:
        that:
          - "'{{ linux_user }}' in user_exists.stdout"

    - name: Debug var
      ansible.builtin.debug:
        var: user_exists

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
